language: swift
osx_image: xcode8.3
script:
- carthage update
- xcodebuild test -project RxDratini.xcodeproj -scheme "RxDratini-iOS" -sdk "iphonesimulator" -destination "OS=10.3.1,name=iPhone 7"
- xcodebuild test -project RxDratini.xcodeproj -scheme "RxDratini-macOS" -sdk "macosx" -destination "arch=x86_64"
- xcodebuild -project RxDratini.xcodeproj -scheme "RxDratini-watchOS" -sdk "watchsimulator" -destination "OS=3.2,name=Apple Watch - 42mm"
- xcodebuild test -project RxDratini.xcodeproj -scheme "RxDratini-tvOS" -sdk "appletvsimulator" -destination "OS=10.0,name=Apple TV 1080p"
after_success:
- bash <(curl -s https://codecov.io/bash) -J 'RxDratini' -X xcodeplist

